name: aoc
version: 0.1.0
license: MIT
github: mcwitt/puzzles
author: Matt Wittmann
synopsis: Advent of Code solutions

language: GHC2021

dependencies:
  - base == 4.*
  - containers
  - linear

library:
  source-dirs: src
  exposed-modules:
    - AoC

executables:
  aoc-y2016-d01:
    main: Main.hs
    source-dirs: app/Y2016/D01
    dependencies:
        - aoc
  aoc-y2023-d01:
    main: Main.hs
    source-dirs: app/Y2023/D01
    dependencies:
        - aoc
  aoc-y2023-d02:
    main: Main.hs
    source-dirs: app/Y2023/D02
    dependencies:
        - aoc

# tests:
#   aoc-tests:
#     main: Tests.hs
#     source-dirs: test
#     dependencies:
#       - tasty
#       - tasty-hunit
#       - tasty-quickcheck
