name: aoc
version: 0.1.0
license: MIT
github: mcwitt/puzzles
author: Matt Wittmann
synopsis: Advent of Code solutions

language: GHC2021

ghc-options:
  - -Wunused-binds
  - -Wunused-imports

dependencies:
  - base == 4.*
  - array
  - containers
  - heaps
  - linear
  - MemoTrie
  - mtl
  - recursion-schemes
  - split
  - vector

library:
  source-dirs: src
  exposed-modules:
    - AoC
    - Y2023.D03.Parser

executables:
  aoc-y2016-d01:
    main: Main.hs
    source-dirs: app/Y2016/D01
    dependencies:
        - aoc
  aoc-y2016-d02:
    main: Main.hs
    source-dirs: app/Y2016/D02
    dependencies:
        - aoc
  aoc-y2016-d03:
    main: Main.hs
    source-dirs: app/Y2016/D03
    dependencies:
        - aoc
  aoc-y2016-d04:
    main: Main.hs
    source-dirs: app/Y2016/D04
    dependencies:
        - aoc
  aoc-y2023-d01:
    main: Main.hs
    source-dirs: app/Y2023/D01
    dependencies:
        - aoc
  aoc-y2023-d02:
    main: Main.hs
    source-dirs: app/Y2023/D02
    dependencies:
        - aoc
  aoc-y2023-d03:
    main: Main.hs
    source-dirs: app/Y2023/D03
    dependencies:
        - aoc
  aoc-y2023-d04:
    main: Main.hs
    source-dirs: app/Y2023/D04
    dependencies:
        - aoc
  aoc-y2023-d05:
    main: Main.hs
    source-dirs: app/Y2023/D05
    dependencies:
        - aoc
  aoc-y2023-d06:
    main: Main.hs
    source-dirs: app/Y2023/D06
    dependencies:
        - aoc
  aoc-y2023-d07:
    main: Main.hs
    source-dirs: app/Y2023/D07
    dependencies:
        - aoc
  aoc-y2023-d08:
    main: Main.hs
    source-dirs: app/Y2023/D08
    dependencies:
        - aoc
  aoc-y2023-d09:
    main: Main.hs
    source-dirs: app/Y2023/D09
    dependencies:
        - aoc
  aoc-y2023-d10:
    main: Main.hs
    source-dirs: app/Y2023/D10
    dependencies:
        - aoc
  aoc-y2023-d11:
    main: Main.hs
    source-dirs: app/Y2023/D11
    dependencies:
        - aoc
  aoc-y2023-d12:
    main: Main.hs
    source-dirs: app/Y2023/D12
    dependencies:
        - aoc
  aoc-y2023-d13:
    main: Main.hs
    source-dirs: app/Y2023/D13
    dependencies:
        - aoc
  aoc-y2023-d14:
    main: Main.hs
    source-dirs: app/Y2023/D14
    dependencies:
        - aoc
  aoc-y2023-d15:
    main: Main.hs
    source-dirs: app/Y2023/D15
    dependencies:
        - aoc
  aoc-y2023-d16:
    main: Main.hs
    source-dirs: app/Y2023/D16
    dependencies:
        - aoc
  aoc-y2023-d17:
    main: Main.hs
    source-dirs: app/Y2023/D17
    dependencies:
        - aoc
  aoc-y2023-d18:
    main: Main.hs
    source-dirs: app/Y2023/D18
    dependencies:
        - aoc
  aoc-y2023-d19:
    main: Main.hs
    source-dirs: app/Y2023/D19
    dependencies:
        - aoc

# tests:
#   aoc-tests:
#     main: Tests.hs
#     source-dirs: test
#     dependencies:
#       - tasty
#       - tasty-hunit
#       - tasty-quickcheck
